[package]
name = "zeebe-client"
version = "0.0.1"
authors = ["Mackenzie Clark <mackenzie.a.z.c@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
futures = "0.1.27"
grpc = "0.6.1"
protobuf = "2"
serde = "1.0.91"
serde_json = "1.0.39"
tokio = { version = "0.1.20", optional = true }

[build-dependencies]
protoc-rust-grpc = "0.6.1"

[dev-dependencies]
serde_derive = "1.0.91"

# Include the timer feature by default, which pulls in tokio timer. This seems like a reasonable default. Some users may
# not want to run on tokio or use the tokio timer, so it is made optional.
[features]
default = ["timer"]
timer = ["tokio"]
